# Generated by Django 3.1.5 on 2021-01-28 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('kjv_text', models.CharField(max_length=1000)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_set', to='bible.chapter')),
            ],
        ),
    ]
