# Generated by Django 3.1.5 on 2021-02-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_auto_20210224_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='kjv_verse',
            name='verse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verse_set', to='bible.verse'),
        ),
    ]
