# Generated by Django 3.1.5 on 2021-04-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_auto_20210227_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shorthand',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
