# Generated by Django 3.1.5 on 2021-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0005_book_shorthand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shorthand',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
